/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redhat_et_libguestfs_GuestFS */

#ifndef _Included_com_redhat_et_libguestfs_GuestFS
#define _Included_com_redhat_et_libguestfs_GuestFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_redhat_et_libguestfs_GuestFS__1create
  (JNIEnv *, jobject);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0
 * Signature: (JLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;ZILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0
  (JNIEnv *, jobject, jlong, jstring, jstring, jobjectArray, jboolean, jint, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rint
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rint
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rinterr
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rinterr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rint64
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rint64
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rint64err
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rint64err
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rbool
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rbool
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rboolerr
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rboolerr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rconststring
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rconststring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rconststringerr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rconststringerr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstring
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstringerr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstringerr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstringlist
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstringlist
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstringlisterr
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstringlisterr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstruct
 * Signature: (JLjava/lang/String;)Lcom/redhat/et/libguestfs/PV;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstruct
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstructerr
 * Signature: (J)Lcom/redhat/et/libguestfs/PV;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstructerr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstructlist
 * Signature: (JLjava/lang/String;)[Lcom/redhat/et/libguestfs/PV;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstructlist
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rstructlisterr
 * Signature: (J)[Lcom/redhat/et/libguestfs/PV;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rstructlisterr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rhashtable
 * Signature: (JLjava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rhashtable
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _test0rhashtableerr
 * Signature: (J)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1test0rhashtableerr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _launch
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1launch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _wait_ready
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1wait_1ready
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _kill_subprocess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1kill_1subprocess
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _add_drive
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1add_1drive
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _add_cdrom
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1add_1cdrom
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _add_drive_ro
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1add_1drive_1ro
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _config
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1config
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_qemu
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1qemu
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_qemu
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1qemu
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_path
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1path
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_path
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1path
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_append
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1append
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_append
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1append
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_autosync
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1autosync
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_autosync
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1autosync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_verbose
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1verbose
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_verbose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1verbose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _is_ready
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1is_1ready
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _is_config
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1is_1config
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _is_launching
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1is_1launching
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _is_busy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1is_1busy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_state
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1state
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_busy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1busy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_ready
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1ready
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _end_busy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1end_1busy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_memsize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1memsize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_memsize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1memsize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_pid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1pid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mount
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mount
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _touch
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1touch
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _cat
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1cat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _ll
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1ll
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _ls
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1ls
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _list_devices
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1list_1devices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _list_partitions
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1list_1partitions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _pvs
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1pvs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _vgs
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1vgs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _lvs
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1lvs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _pvs_full
 * Signature: (J)[Lcom/redhat/et/libguestfs/PV;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1pvs_1full
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _vgs_full
 * Signature: (J)[Lcom/redhat/et/libguestfs/VG;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1vgs_1full
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _lvs_full
 * Signature: (J)[Lcom/redhat/et/libguestfs/LV;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1lvs_1full
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _read_lines
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1read_1lines
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_init
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1init
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_defvar
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1defvar
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_defnode
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/redhat/et/libguestfs/IntBool;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1defnode
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_get
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1get
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_set
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1set
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_insert
 * Signature: (JLjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1insert
  (JNIEnv *, jobject, jlong, jstring, jstring, jboolean);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_rm
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1rm
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_mv
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1mv
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_match
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1match
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_save
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1save
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_load
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1load
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _aug_ls
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1aug_1ls
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _rm
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1rm
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _rmdir
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1rmdir
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _rm_rf
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1rm_1rf
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkdir
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkdir
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkdir_p
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkdir_1p
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _chmod
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1chmod
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _chown
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1chown
  (JNIEnv *, jobject, jlong, jint, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _exists
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1exists
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _is_file
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1is_1file
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _is_dir
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1is_1dir
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _pvcreate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1pvcreate
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _vgcreate
 * Signature: (JLjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1vgcreate
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _lvcreate
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1lvcreate
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkfs
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkfs
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sfdisk
 * Signature: (JLjava/lang/String;III[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sfdisk
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint, jobjectArray);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _write_file
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1write_1file
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _umount
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1umount
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mounts
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mounts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _umount_all
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1umount_1all
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _lvm_remove_all
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1lvm_1remove_1all
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _file
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1file
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _command
 * Signature: (J[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1command
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _command_lines
 * Signature: (J[Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1command_1lines
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _stat
 * Signature: (JLjava/lang/String;)Lcom/redhat/et/libguestfs/Stat;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1stat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _lstat
 * Signature: (JLjava/lang/String;)Lcom/redhat/et/libguestfs/Stat;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1lstat
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _statvfs
 * Signature: (JLjava/lang/String;)Lcom/redhat/et/libguestfs/StatVFS;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1statvfs
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _tune2fs_l
 * Signature: (JLjava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_redhat_et_libguestfs_GuestFS__1tune2fs_1l
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_setro
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1setro
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_setrw
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1setrw
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_getro
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1getro
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_getss
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1getss
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_getbsz
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1getbsz
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_setbsz
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1setbsz
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_getsz
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1getsz
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_getsize64
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1getsize64
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_flushbufs
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1flushbufs
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _blockdev_rereadpt
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1blockdev_1rereadpt
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _upload
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1upload
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _download
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1download
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _checksum
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1checksum
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _tar_in
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1tar_1in
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _tar_out
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1tar_1out
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _tgz_in
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1tgz_1in
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _tgz_out
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1tgz_1out
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mount_ro
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mount_1ro
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mount_options
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mount_1options
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mount_vfs
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mount_1vfs
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _debug
 * Signature: (JLjava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1debug
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _lvremove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1lvremove
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _vgremove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1vgremove
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _pvremove
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1pvremove
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_e2label
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1e2label
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_e2label
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1e2label
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _set_e2uuid
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1set_1e2uuid
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _get_e2uuid
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1get_1e2uuid
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _fsck
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1fsck
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _zero
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1zero
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _grub_install
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1grub_1install
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _cp
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1cp
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _cp_a
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1cp_1a
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mv
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mv
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _drop_caches
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1drop_1caches
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _dmesg
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1dmesg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _ping_daemon
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1ping_1daemon
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _equal
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redhat_et_libguestfs_GuestFS__1equal
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _strings
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1strings
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _strings_e
 * Signature: (JLjava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1strings_1e
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _hexdump
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1hexdump
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _zerofree
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1zerofree
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _pvresize
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1pvresize
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sfdisk_N
 * Signature: (JLjava/lang/String;IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sfdisk_1N
  (JNIEnv *, jobject, jlong, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sfdisk_l
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sfdisk_1l
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sfdisk_kernel_geometry
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sfdisk_1kernel_1geometry
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sfdisk_disk_geometry
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sfdisk_1disk_1geometry
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _vg_activate_all
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1vg_1activate_1all
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _vg_activate
 * Signature: (JZ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1vg_1activate
  (JNIEnv *, jobject, jlong, jboolean, jobjectArray);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _lvresize
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1lvresize
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _resize2fs
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1resize2fs
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _find
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1find
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _e2fsck_f
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1e2fsck_1f
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sleep
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sleep
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _ntfs_3g_probe
 * Signature: (JZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1ntfs_13g_1probe
  (JNIEnv *, jobject, jlong, jboolean, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sh
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sh
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sh_lines
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sh_1lines
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _glob_expand
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1glob_1expand
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _scrub_device
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1scrub_1device
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _scrub_file
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1scrub_1file
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _scrub_freespace
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1scrub_1freespace
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkdtemp
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkdtemp
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _wc_l
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1wc_1l
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _wc_w
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1wc_1w
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _wc_c
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1wc_1c
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _head
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1head
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _head_n
 * Signature: (JILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1head_1n
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _tail
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1tail
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _tail_n
 * Signature: (JILjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1tail_1n
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _df
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1df
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _df_h
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redhat_et_libguestfs_GuestFS__1df_1h
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _du
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_redhat_et_libguestfs_GuestFS__1du
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _initrd_list
 * Signature: (JLjava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1initrd_1list
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mount_loop
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mount_1loop
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkswap
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkswap
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkswap_L
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkswap_1L
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkswap_U
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkswap_1U
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mknod
 * Signature: (JIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mknod
  (JNIEnv *, jobject, jlong, jint, jint, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mkfifo
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mkfifo
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mknod_b
 * Signature: (JIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mknod_1b
  (JNIEnv *, jobject, jlong, jint, jint, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _mknod_c
 * Signature: (JIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1mknod_1c
  (JNIEnv *, jobject, jlong, jint, jint, jint, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _umask
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_redhat_et_libguestfs_GuestFS__1umask
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _readdir
 * Signature: (JLjava/lang/String;)[Lcom/redhat/et/libguestfs/Dirent;
 */
JNIEXPORT jobjectArray JNICALL Java_com_redhat_et_libguestfs_GuestFS__1readdir
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_redhat_et_libguestfs_GuestFS
 * Method:    _sfdiskM
 * Signature: (JLjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redhat_et_libguestfs_GuestFS__1sfdiskM
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
