#!/bin/sh

set -e

case "$1" in
    purge)
        rm -f \
            /usr/lib/guestfs/supermin.d/hostfiles \
            /usr/lib/guestfs/supermin.d/hostfiles-t \
            /usr/lib/guestfs/supermin.d/base.img
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
