usr/bin/virt-*
usr/share/man/man1/virt-*
usr/share/man/*/man1/virt-*
usr/lib/*-*/virt-p2v
usr/share/virt-p2v

usr/share/bash-completion/completions/virt-*

etc/libguestfs-tools.conf
etc/xdg/virt-builder
etc/virt-builder

usr/share/man/man5/libguestfs-tools.conf*
usr/share/man/*/man5/libguestfs-tools.conf*

usr/bin/libguestfs-test-tool
usr/share/man/man1/libguestfs-test-tool*
usr/share/man/*/man1/libguestfs-test-tool*

usr/share/doc/libguestfs/example-*.xml
usr/share/doc/libguestfs/virt-inspector.rng

usr/sbin/libguestfs-make-fixed-appliance
usr/share/man/man1/libguestfs-make-fixed-appliance*
usr/share/man/*/man1/libguestfs-make-fixed-appliance*

usr/bin/guestfish
usr/share/man/man1/guestfish*
usr/share/man/*/man1/guestfish*

usr/share/bash-completion/completions/guestfish

usr/bin/guestmount
usr/share/man/man1/guestmount*
usr/share/man/*/man1/guestmount*
usr/bin/guestunmount
usr/share/man/man1/guestunmount*
usr/share/man/*/man1/guestunmount*

usr/share/bash-completion/completions/guest*mount
