=encoding utf8

=head1 名前

guestfs-ruby - Ruby から libguestfs を使用する方法

=head1 書式

 require 'guestfs'
 g = Guestfs::Guestfs.new()
 g.add_drive_opts("disk.img",
                  :readonly => 1, :format => "raw")
 g.launch()

=head1 説明

This manual page documents how to call libguestfs from the Ruby programming
language.  This page just documents the differences from the C API and gives
some examples.  If you are not familiar with using libguestfs, you also need
to read L<guestfs(3)>.

=head2 例外

Errors from libguestfs functions are mapped into the C<Error> exception.
This has a single parameter which is the error message (a string).

=head1 例 1: ディスクイメージの作成

@EXAMPLE1@

=head1 例 2: 仮想マシンのディスクイメージの検査

@EXAMPLE2@

=head1 関連項目

L<guestfs(3)>, L<guestfs-examples(3)>, L<guestfs-erlang(3)>,
L<guestfs-java(3)>, L<guestfs-ocaml(3)>, L<guestfs-perl(3)>,
L<guestfs-python(3)>, L<guestfs-recipes(1)>, L<http://libguestfs.org/>。

=head1 著者

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 COPYRIGHT

Copyright (C) 2010 Red Hat Inc. L<http://libguestfs.org/>

このマニュアルページにある例は、なんら制限なく自由にコピー、修正、配布できます。

This library is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.

This library is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library; if not, write to the Free Software Foundation,
Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

