=encoding utf8

=begin コメント

読みやすさを向上させるために、慣習を破り、セクション見出しをすべて大文字にしてはいません。

=end コメント

=head1 名前

guestfs-recipes - libguestfs, guestfish および仮想化ツールのレシピ

=head1 説明

このページには libguestfs, L<guestfish(1)> および仮想化ツールを使用してできることのレシピとリンクがあります。

=head1 仮想マシンの setuid ファイルを監査します

See: L<virt-ls(1)/EXAMPLES>.

=head1 Windows XP 仮想マシンの背景画像を変更します

以下のリンクは、Windows XP 仮想マシンのユーザーの背景画像を変更するために L<guestfish(1)>
を使用する方法について説明しています。残念ながら、このテクニックは Windows のバージョンによりわずかに異なります。

L<https://lists.fedoraproject.org/pipermail/virt/2011-May/002655.html>
L<https://lists.fedoraproject.org/pipermail/virt/2011-May/002658.html>

=head1 Checksum a file or device within a disk image

To checksum a whole device, or a partition, LV etc within a disk image:

 guestfish --ro -a disk.img run : checksum-device md5 /dev/sda1

Replace C<md5> with the type of checksum you want.  See
L<guestfs(3)/guestfs_checksum_device> for a list of supported types.

C</dev/sda1> means "the first partition".  You could use C</dev/sda> to
checksum the whole disk image, or the name of a logical volume or RAID
device.

To checksum a single file:

 guestfish --ro -a disk.img -i checksum sha256 /etc/passwd

or for a Windows guest:

 guestfish --ro -a disk.img -i \
   checksum sha256 'win:\windows\system32\config\SOFTWARE'

=head1 Cloning a virtual machine

Use a combination of tools like L<cp(1)>, L<dd(1)>, and virt tools like
L<virt-sysprep(1)>, L<virt-sparsify(1)> and L<virt-resize(1)>.

For more details, see: L<virt-sysprep(1)/COPYING AND CLONING>.

=head1 CD-ROM / DVD / ISO を tar ファイルに変換します

入力 C<cd.iso> を出力 C<cd.tar.gz> に変換します:

 guestfish --ro -a cd.iso -m /dev/sda tgz-out / cd.tar.gz

サブディレクトリ（例: C</files>）をエクスポートするには:

 guestfish --ro -a cd.iso -m /dev/sda tgz-out /files cd.tar.gz

=head1 空のディスクイメージを作成します

The L<virt-format(1)> tool can do this directly.

Use L<virt-make-fs(1)> to create a disk image with content.  This can also
create some standard disk images such as virtual floppy devices (VFDs).

You can also use the L<guestfish(1)> I<-N> option to create empty disk
images.  The useful guide below explains the options available.

L<https://rwmj.wordpress.com/2010/09/08/new-guestfish-n-options-in-1-5-9/#content>

=head1 Delete a file (or other simple file operations)

Use guestfish.  To delete a file:

 guestfish -a disk.img -i rm /file/to/delete

To touch a file (bring it up to date or create it):

 guestfish -a disk.img -i touch /file/to/touch

To stat a file.  Since this is a read-only operation, we can make it safer
by adding the I<--ro> flag.

 guestfish --ro -a disk.img -i stat /file/to/stat

There are dozens of these commands.  See L<guestfish(1)> or the output of
C<guestfish -h>

=head1 ディスクイメージまたは仮想マシンの中にあるファイルシステムの内容をそのままダンプします

You can use the L<guestfish(1)> C<download> command to extract the raw
filesystem content from any filesystem in a disk image or a VM (even one
which is encrypted or buried inside an LV or RAID device):

 guestfish --ro -a disk.img run : download /dev/sda1 sda1.img

 guestfish --ro -d Guest run : download /dev/vg_guest/lv_root lv.img

To download to stdout, replace the filename with a C<-> character:

 guestfish --ro -a disk.img run : download /dev/sda1 - | hexdump -C

ディスクイメージにあるファイルシステムを一覧表示するには L<virt-filesystems(1)> を使用します。

=head1 仮想マシンの GRUB 設定を編集します

次の目的のために実行できます:

=over 4

=item *

起動しない仮想マシンを修正します。

=item *

仮想マシンの起動時に使用するカーネルを変更します。

=item *

カーネルのコマンドラインオプションを変更します。

=back

GRUB 設定を編集するには L<virt-edit(1)> を使用します:

 virt-edit -d BrokenGuest /boot/grub2/grub.cfg

もしくは、起動不可能な仮想マシンの中から一般的に修復するために、このように L<virt-rescue(1)> を使用します:

 virt-rescue -d BrokenGuest

=head1 仮想マシンから任意のディレクトリをエクスポートします

仮想マシンから C</home> をローカルディレクトリにエクスポートするには L<virt-copy-out(1)> を使用します:

 virt-copy-out -d Guest /home .

注:

=over 4

=item *

コマンドの最後のドットは表示エラーではありません。現在のディレクトリーにコピーしたいことを意味します。

=item *

これは現在のディレクトリーに C<home> というディレクトリーを作成します。

=back

仮想マシンが Windows ならば、ドライブレターとバックスラッシュを使用できます。しかし、パスを C<win:>
で始める必要があり、シェルから保護するために引用符でくくる必要があります。このようにします:

 virt-copy-out -d WinGuest 'win:c:\windows\system32\config' .

圧縮された tar ファイルとして出力を取得するには:

 virt-tar-out -d Guest /home - | gzip --best > home.tar.gz

Although it sounds tempting, this is usually not a reliable way to get a
backup from a running guest.  See the entry in the FAQ:
L<http://libguestfs.org/FAQ.html#backup>

=head1 もっとも領域を使用しているユーザーを検索します

この簡単なスクリプトは、ホームディレクトリーにおいてもっとも領域を使用しているユーザーを検索するために、Linux 仮想マシンを検査します。

 #!/bin/sh -
 
 set -e
 
 vm="$1"
 dir=/home
 
 eval $(guestfish --ro -d "$vm" -i --listen)
 
 for d in $(guestfish --remote ls "$dir"); do
     echo -n "$dir/$d"
     echo -ne '\t'
     guestfish --remote du "$dir/$d";
 done | sort -nr -k 2
 
 guestfish --remote exit

=head1 仮想マシンから DHCP アドレスを取得します

以下のリンクは、仮想マシンに対して最後に割り当てられた DHCP アドレスを取得するために、多くの異なる利用可能なテクニックを説明しています。

L<https://rwmj.wordpress.com/2011/03/31/tip-code-for-getting-dhcp-address-from-a-virtual-machine-disk-image/#content>

libguestfs のソースのサンプルディレクトリーに、C<virt-dhcp-address.c> プログラムの最新バージョンがあります。

=head1 オペレーティングシステムの製品名を取得します

以下のスクリプトを C<product-name.sh> というファイルの中に保存します:

 #!/bin/sh -
 set -e
 eval "$(guestfish --ro -d "$1" --i --listen)"
 root="$(guestfish --remote inspect-get-roots)"
 guestfish --remote inspect-get-product-name "$root"
 guestfish --remote exit

スクリプトを実行可能にして、名前付き仮想マシンにおいて実行します:

 # product-name.sh RHEL60x64
 Red Hat Enterprise Linux Server release 6.0 (Santiago)

C<xpath> コマンドラインツールを使用して、またはお気に入りのプログラミング言語から、L<virt-inspector(1)> XML において
XPath クエリーを使用することもできます:

 # virt-inspector RHEL60x64 > xml
 # xpath '//product_name' < xml
 Found 1 nodes:
 -- NODE --
 <product_name>Red Hat Enterprise Linux Server release 6.0 (Santiago)</product_name>

=head1 Linux 仮想マシンのデフォルトの起動カーネルを取得します

以下のリンクに Linux 仮想マシンのデフォルトの起動カーネルを表示するためのプログラムがあります。

L<https://rwmj.wordpress.com/2010/10/30/tip-use-augeas-to-get-the-default-boot-kernel-for-a-vm/#content>

Augeas を使用します。また、以下のように、多くのさまざまな作業に対して適用可能な一般的なテクニックがあります:

=over 4

=item *

仮想マシンのユーザーアカウントの一覧

=item *

使用するよう設定されたリポジトリー

=item *

接続する NTP サーバー

=item *

前回起動時の起動メッセージ

=item *

最近ログインしたユーザーの一覧

=back

L<http://augeas.net/>

=head1 仮想マシンに RPM をインストールします

以下のリンクは、仮想マシンにおいて RPM をインストールする方法があります。実際、仮想マシンの次回起動時にインストールされる "firstboot"
スクリプトを用いて仮想マシンに RPM
がアップロードされます。停止中の仮想マシンにおいて致命的なセキュリティ更新をインストールするためにこのテクニックを使用できます。

L<https://rwmj.wordpress.com/2010/12/01/tip-install-rpms-in-a-guest/#content>

=head1 仮想マシンにインストールされているアプリケーションを一覧表示します

以下をファイル C<list-apps.sh> に保存します:

 #!/bin/sh -
 set -e
 eval "$(guestfish --ro -d "$1" --i --listen)"
 root="$(guestfish --remote inspect-get-roots)"
 guestfish --remote inspect-list-applications "$root"
 guestfish --remote exit

ファイルを実行可能にして、あらゆる名前付き仮想マシンにおいて実行できます:

 # list-apps.sh WinGuest
 [0] = {
   app_name: Mozilla Firefox (3.6.12)
   app_display_name: Mozilla Firefox (3.6.12)
   app_epoch: 0
   app_version: 3.6.12 (en-GB)
   app_release:
   app_install_path: C:\Program Files\Mozilla Firefox
   app_trans_path:
   app_publisher: Mozilla
   app_url: http://www.mozilla.com/en-GB/
   app_source_package:
   app_summary:
   app_description: Mozilla Firefox
 }
 [1] = {
   app_name: VLC media player
   app_display_name: VLC media player 1.1.5
   app_epoch: 0
   app_version: 1.1.5
   app_release:
   app_install_path: C:\Program Files\VideoLAN\VLC
   app_trans_path:
   app_publisher: VideoLAN
   app_url: http://www.videolan.org/
   app_source_package:
   app_summary:
   app_description:
 }

（libvirt 仮想マシンの代わりに）ディスクイメージにおいてスクリプトを実行したいならば、C<-d "$1"> を C<-a "$1">
に変更します。L<virt-inspector(1)> 参照。

=head1 仮想マシンのファイルおよびディレクトリを一覧表示します

Use L<virt-ls(1)>.

=head1 Windows 仮想マシンのサービスを一覧表示します

以下のリンクは、Windows
仮想マシンからサービスを、およびそれらのサービスが起動時に実行されるか必要に応じて読み込まれるかを一覧化するために使用できるスクリプトがあります。

L<https://rwmj.wordpress.com/2010/12/10/tip-list-services-in-a-windows-guest/#content>

=head1 ディスクイメージをスパースにします

Use L<virt-sparsify(1)>.

=head1 ディスク使用量を時系列に監視します

時系列で仮想マシンのディスク使用量を監視するために L<virt-df(1)> を使用できます。以下のリンクは仮想マシンを含みます。

L<http://virt-tools.org/learning/advanced-virt-df/>

=head1 Windows Vista （またそれ以降）から Windows のイベントログを読み出します

L<guestfish(1)> に加えて以下のリンクに示されるツールは、実行中の Windows Vista およびそれ以降のあらゆる仮想マシンから
Windows イベントログを読み出すために使用できます。

L<https://rwmj.wordpress.com/2011/04/17/decoding-the-windows-event-log-using-guestfish/#content>

=head1 root のパスワードを削除します (Linux)

L<virt-edit(1)> I<-e> を使用することにより、ファイルの内容を簡単に置き換えることができます。一つの使用方法は Linux
仮想マシンから root パスワードを削除することです。

 virt-edit domname /etc/passwd -e 's/^root:.*?:/root::/'

=head1 Administrator のパスワードを削除します (Windows)

以下のリンクは、Windows
仮想マシンから管理者パスワードを削除するためのテクニックを含みます。または、より精細にするために、セキュリティを迂回するために使用でき、次回ログイン時にコマンドプロンプトを出します:

L<https://mdbooth.wordpress.com/2010/10/18/resetting-a-windows-guests-administrator-password-with-guestfish/>

=head1 Sysprepping a virtual machine (Windows)

It is possible to do a "sysprep" using libguestfs alone, although not
straightforward.  Currently there is code in the Aeolus Oz project which
does this (using libguestfs).  It is likely we will add this to
L<virt-sysprep(1)> in future.

L<https://github.com/clalancette/oz>
L<https://www.redhat.com/archives/virt-tools-list/2011-May/msg00019.html>

=head1 Live CD を展開します

Linux live CD
は、ロシア人形のように覆われた複数の層のディスクイメージを含みます。以下のガイドに概要が示されたように、これらの複数の層の内側を見るために
L<guestfish(1)> を使用できます。

L<https://rwmj.wordpress.com/2009/07/15/unpack-the-russian-doll-of-a-f11-live-cd/#content>

=head1 ファイルのアップロード方法およびダウンロード方法

以下のリンクは、仮想マシンにファイルをアップロード、および仮想マシンからファイルをダウンロードすることに関する、一般的なヒントがあります。

L<https://rwmj.wordpress.com/2010/12/02/tip-uploading-and-downloading/#content>

=head1 VMware ESX 仮想マシンにおいて libguestfs ツールを使用します

以下のリンクは、まず最初に sshfs 経由で VMware VMFS を共有することにより、VMware ESX 仮想マシンにおいて
libguestfs, L<guestfish(1)> および virt ツールを使用する方法を説明しています。

L<https://rwmj.wordpress.com/2011/05/10/tip-use-libguestfs-on-vmware-esx-guests/#content>

=head1 関連項目

L<guestfs(3)>, L<guestfish(1)>, L<guestfs-examples(3)>,
L<guestfs-erlang(3)>, L<guestfs-java(3)>, L<guestfs-ocaml(3)>,
L<guestfs-perl(3)>, L<guestfs-python(3)>, L<guestfs-ruby(3)>,
L<http://libguestfs.org/>.

=head1 著者

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 COPYRIGHT

Copyright (C) 2009-2012 Red Hat Inc.

