=encoding utf8

=head1 НАЗВА

guestfs-perl - How to use libguestfs from Perl

=head1 КОРОТКИЙ ОПИС

 use Sys::Guestfs;
 
 my $g = Sys::Guestfs->new ();
 $g->add_drive_opts ('guest.img', format => 'raw');
 $g->launch ();
 $g->mount_options ('', '/dev/sda1', '/');
 $g->touch ('/hello');
 $g->shutdown ();
 $g->close ();

=head1 ОПИС

This manual page documents how to call libguestfs from the Perl programming
language.  This page just documents the differences from the C API and gives
some examples.  If you are not familiar with using libguestfs, you also need
to read L<guestfs(3)>.  To read the full Perl API, see L<Sys::Guestfs(3)>.

=head2 ПОМИЛКИ

Errors from libguestfs functions turn into calls to C<croak> (see
L<Carp(3)>).

=head1 ПРИКЛАД 1. СТВОРЕННЯ ОБРАЗУ ДИСКА

@EXAMPLE1@

=head1 ПРИКЛАД 2. ПЕРЕВІРКА ОБРАЗУ ДИСКА ВІРТУАЛЬНОЇ МАШИНИ

@EXAMPLE2@

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<Sys::Guestfs(3)>, L<guestfs(3)>, L<guestfs-examples(3)>,
L<guestfs-erlang(3)>, L<guestfs-java(3)>, L<guestfs-ocaml(3)>,
L<guestfs-python(3)>, L<guestfs-recipes(1)>, L<guestfs-ruby(3)>,
L<http://libguestfs.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc. L<http://libguestfs.org/>, 2011

The examples in this manual page may be freely copied, modified and
distributed without any restrictions.

This library is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.

Ця бібліотека поширюється у сподіванні, що вона буде корисною, але БЕЗ
БУДЬ-ЯКИХ ГАРАНТІЙНИХ ЗОБОВ’ЯЗАНЬ; навіть без очевидної гарантії
ПРАЦЕЗДАТНОСТІ або ПРИДАТНОСТІ ДЛЯ ВИКОРИСТАННЯ З ПЕВНОЮ МЕТОЮ. Докладніше
про це можна дізнатися з GNU General Public License.

Ви маєте отримати копію GNU Lesser General Public License разом з цією
бібліотекою; якщо це не так, повідомте про факт за адресою Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
USA

