=encoding utf8

=head1 НАЗВА

guestfs-ruby - How to use libguestfs from Ruby

=head1 КОРОТКИЙ ОПИС

 require 'guestfs'
 g = Guestfs::Guestfs.new()
 g.add_drive_opts("disk.img",
                  :readonly => 1, :format => "raw")
 g.launch()

=head1 ОПИС

This manual page documents how to call libguestfs from the Ruby programming
language.  This page just documents the differences from the C API and gives
some examples.  If you are not familiar with using libguestfs, you also need
to read L<guestfs(3)>.

=head2 ВИНЯТКИ

Errors from libguestfs functions are mapped into the C<Error> exception.
This has a single parameter which is the error message (a string).

=head1 ПРИКЛАД 1. СТВОРЕННЯ ОБРАЗУ ДИСКА

@EXAMPLE1@

=head1 ПРИКЛАД 2. ПЕРЕВІРКА ОБРАЗУ ДИСКА ВІРТУАЛЬНОЇ МАШИНИ

@EXAMPLE2@

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfs(3)>, L<guestfs-examples(3)>, L<guestfs-erlang(3)>,
L<guestfs-java(3)>, L<guestfs-ocaml(3)>, L<guestfs-perl(3)>,
L<guestfs-python(3)>, L<guestfs-recipes(1)>, L<http://libguestfs.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2010–2012

