
=head1 НАЗВА

guestfs-erlang — як користуватися libguestfs з програми мовою Erlang

=head1 КОРОТКИЙ ОПИС

 {ok, G} = guestfs:create(),
 ok = guestfs:add_drive_opts(G, Disk,
                             [{format, "raw"}, {readonly, true}]),
 ok = guestfs:launch(G),
 [Device] = guestfs:list_devices(G),
 ok = guestfs:close(G).

=head1 ОПИС

На цій сторінці підручника наведено документацію щодо викликів libguestfs з
коду мовою програмування Erlang. На сторінці задокументовано відмінності від
програмного інтерфейсу C та подано декілька прикладів. Якщо ви не дуже
знайомі із користуванням libguestfs, вам також слід прочитати підручник з
L<guestfs(3)>.

=head2 ВІДКРИТТЯ І ЗАКРИТТЯ ДЕСКРИПТОРА

Прив'язки до Erlang реалізовано за допомогою зовнішньої програми із назвою
C<erl-guestfs>. Ця програма має зберігатися у одному з каталогів PATH,
інакше вам доведеться вказати повний шлях до програми:

 {ok, G} = guestfs:create().

 {ok, G} = guestfs:create("/шлях/до/erl-guestfs").

C<G> є дескриптором libguestfs, який вам слід передавати іншим функціям.

Закриття обробника:

 ok = guestfs:close(G).

=head2 ФУНКЦІЇ І НЕОБОВ'ЯЗКОВІ ПАРАМЕТРИ

Якщо функція приймає необов'язкові аргументи, першими слід вказувати
обов'язкові. Останнім аргументом є список кортежів, яким надається список
решти необов'язкових аргументів.

 ok = guestfs:add_drive_opts(G, Disk,
                             [{format, "raw"}, {readonly, true}]).

Якщо останнім аргументом має бути порожній список, ви також можете його
пропустити:

 ok = guestfs:add_drive_opts(G, Disk).

=head2 ЗНАЧЕННЯ, ЩО ПОВЕРТАЮТЬСЯ, І ПОМИЛКИ

Якщо дію виконано успішно, більшість функцій повертають значення C<Result>
(ним може бути список, рядок, кортеж тощо).  Якщо у функції немає чого
повернути, буде повернуто атом C<ok>.

Якщо станеться помилка, ви маєте побачити один із таких кортежів:

=over 4

=item C<{помилка, повідомлення, номер_помилки}>

Позначає звичайну помилку у функції.

C<Повідомлення> — повідомлення про помилку (рядок), а C<номер_помилки> —
номер помилки Unix (ціле число).

C<Errno> може бути нульовим. Див. L<guestfs(3)/guestfs_last_errno>.

=item C<{unknown, Функція}>

Це означає, що викликана вами функція є невідомою. Загалом, таке
трапляється, якщо ви використовуєте C<erl-guestfs> з іншої версії
libguestfs. Не слід так робити.

C<Функція> — назва невідомої функції.

=item C<{unknownarg, Аргумент}>

Це означає, що ви викликали функцію із необов'язковими аргументами,
використавши невідому назву аргументу.

C<Аргумент> — назва невідомого аргументу.

=back

=head1 ПРИКЛАД 1. СТВОРЕННЯ ОБРАЗУ ДИСКА

@EXAMPLE1@

=head1 ПРИКЛАД 2. ПЕРЕВІРКА ОБРАЗУ ДИСКА ВІРТУАЛЬНОЇ МАШИНИ

@EXAMPLE2@

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfs(3)>, L<guestfs-examples(3)>, L<guestfs-gobject(3)>,
L<guestfs-golang(3)>, L<guestfs-java(3)>, L<guestfs-lua(3)>,
L<guestfs-ocaml(3)>, L<guestfs-perl(3)>, L<guestfs-python(3)>,
L<guestfs-recipes(1)>, L<guestfs-ruby(3)>, L<http://www.erlang.org/>.
L<http://libguestfs.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2011–2012

