
=head1 НАЗВА

libguestfs-make-fixed-appliance - створити базову систему для libguestfs

=head1 КОРОТКИЙ ОПИС

 libguestfs-make-fixed-appliance [--параметри] КАТАЛОГ_ВИВЕДЕННЯ

 libguestfs-make-fixed-appliance [--параметри] --xz

=head1 ОПИС

libguestfs-make-fixed-appliance надає вам змогу створити попередньо зібрану
бінарну базову систему для libguestfs.

B<Зауважте, що у звичайних користувачів не повинно виникнути потреби у
запуску цієї програми>.

Декілька причин, з яких у вас I<може> виникнути потребу у використанні цього
інструмента:

=over 4

=item *

Ви хочете створити самодостатню базову систему libguestfs, яку можна
скопіювати на інший комп'ютер або платформу, де не передбачено підтримки
L<supermin(1)>.

=item *

На вашому комп'ютері декілька користувачів і ви хочете уникнути дублювання
сховища даних або додаткової затримки через наявність декількох кешованих
копій базової системи.

=item *

Вам потрібна дуже передбачувана щодо швидкодії система з libguestfs
(див. L<guestfs-performance(1)>).

=back

Щоб краще зрозуміти потребу у цьому інструменті, ознайомтеся із розділом
L<guestfs-internals(1)/БАЗОВА СИСТЕМА>.

Замість використання цього інструмента, ви можете отримати базові системи зі
сторінки  L<http://libguestfs.org/download/binaries/appliance/>.  Ці базові
системи було створено за допомогою цього інструмента.

Передбачено два способи використання цього інструмента.

=over 4

=item *

Вказати каталог виведення даних, приклад:

 libguestfs-make-fixed-appliance /usr/local/lib/guestfs/appliance

Якщо каталогу виведення даних ще не існує, його буде створено. У цьому
каталозі буде створено чотири файли:

 <OUTPUTDIR>/kernel
 <OUTPUTDIR>/initrd
 <OUTPUTDIR>/root
 <OUTPUTDIR>/README.fixed

Зауважте, що C<I<КАТАЛОГ_ВИВЕДЕННЯ>/root> є розрідженим файлом, отже, слід
бути обережним з його копіюванням.

Після цього ви зможете запускати libguestfs (можливо, після копіювання цього
каталогу на інший комп'ютер) після встановлення для змінної середовища
LIBGUESTFS_PATH значення C<КАТАЛОГ_ВИВЕДЕННЯ>.

=item *

Альтернативним підходом є використання параметра I<--xz> для створення
стисненого архіву:

 libguestfs-make-fixed-appliance --xz

Буде створено архів у I<поточному> каталозі з назвою:

 appliance-<ВЕРСІЯ>.tar.xz

(де C<ВЕРСІЯ> — версія libguestfs). У архіві міститься чотири файла:

 appliance/kernel
 appliance/initrd
 appliance/root
 appliance/README.fixed

Зауважте, що C<appliance/root> є розрідженим файлом, тому слід бути
обережним під час його копіювання.

=back

=head1 ПАРАМЕТРИ

=over 4

=item B<--help>

Показати коротку довідку з користування і завершити роботу.

=item B<-V>

=item B<--version>

Показати дані щодо версії і завершити роботу.

=item B<--xz>

Замість створення базової системи у каталозі виведення результатів, створити
стиснений архів базової системи у поточному каталозі із назвою
F<appliance-I<ВЕРСІЯ>.tar.xz>, де C<ВЕРСІЯ> — це версія libguestfs.

Використання I<--xz> може потребувати додаткового часу. Якщо все буде
нормально, інструмент спрацює без будь-яких додаткових повідомлень.

=back

=head1 УМОВИ ЛІЦЕНЗУВАННЯ

Базова система є повним бінарним дистрибутивом Linux. Якщо ви поширюватимете
його, можливо, вам доведеться поширювати також відповідні файли з початковим
кодом, щоб зберегти сумісність із умовами ліцензування програмного
забезпечення у базовій системі (зокрема GNU General Public License).

=head1 СТАН ВИХОДУ

libguestfs-make-fixed-appliance повертає I<0>, якщо базову систему було
зібрано без помилок.

=head1 ЗМІННІ СЕРЕДОВИЩА

Повний список змінних середовища, які можуть вплинути на роботу libguestfs,
можна знайти на сторінці підручника L<guestfs(3)>.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfs(3)>, L<supermin(1)>, L<xz(1)>, L<http://libguestfs.org/>,
L<http://qemu.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

Copyright (C) 2009-2019 Red Hat Inc.

