
=head1 НАЗВА

virt-copy-out — копіювання файлів і каталогі з образу диска віртуальної
машини.

=head1 КОРОТКИЙ ОПИС

 virt-copy-out -a диск.img /файл|каталог [/файл|каталог ...] локальний_каталог

 virt-copy-out -d домен /файл|каталог [/файл|каталог ...] локальний_каталог

=head1 ОПИС

C<virt-copy-out> копіює файли та каталоги з образу диска віртувальної машини
або іменованого домену libvirt.

У рядку команди можна вказати одну або декілька назв файлів або
каталогів. Каталоги буде скопійовано рекурсивно.

=head1 ПРИКЛАДИ

Отримання домашніх каталогів з віртуальної машини:

 mkdir homes
 virt-copy-out -d MyGuest /home homes

=head1 ПРОСТО СКРИПТ КОМАНДНОЇ ОБОЛОНКИ, ОБГОРТКА НАВКОЛО GUESTFISH

Ця програма є простим скриптом командної оболонки, обгорткою навколо команди
C<copy-out> L<guestfish(1)>. Якщо вам потрібно виконати якесь завдання,
складніше за звичайне копіювання, ймовірно, варто скористатися guestfish
безпосередньо.

=head1 ПАРАМЕТРИ

Оскільки скрипт командної оболонки лише передає параметри безпосередньо до
guestfish, ознайомтеся зі сторінкою підручника для L<guestfish(1)>, щоб
дізнатися більше про повний набір параметрів.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfish(1)>, L<virt-cat(1)>, L<virt-copy-in(1)>, L<virt-edit(1)>,
L<virt-tar-in(1)>, L<virt-tar-out(1)>, L<http://libguestfs.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2011–2012

