
=head1 НАЗВА

virt-log - Display log files from a virtual machine

=head1 КОРОТКИЙ ОПИС

 virt-log [--options] -d domname

 virt-log [--options] -a disk.img [-a disk.img ...]

=head1 ОПИС

C<virt-log> is a command line tool to display the log files from the named
virtual machine (or disk image).

This tool understands and displays both plain text log files
(eg. F</var/log/messages>) and binary formats such as the systemd journal.

To display other types of files, use L<virt-cat(1)>.  To follow (tail)  text
log files, use L<virt-tail(1)>.  To copy files out of a virtual machine, use
L<virt-copy-out(1)>.  To display the contents of the Windows Registry, use
L<virt-win-reg(1)>.

=head1 ПРИКЛАДИ

Показ журналу з гостьової системи повністю:

 virt-log -d mydomain | less

Визначення IP-адреси DHCP, використаної віртуальною машиною:

 virt-log -d mydomain | grep 'dhclient.*bound to'

=head1 ПАРАМЕТРИ

=over 4

=item B<--help>

Показати коротку довідку.

=item B<-a> файл

=item B<--add> файл

Add I<file> which should be a disk image from a virtual machine.  If the
virtual machine has multiple block devices, you must supply all of them with
separate I<-a> options.

Формат образу диска визначається автоматично. Щоб перевизначити його і
примусово використати певний формат, скористайтеся параметром
I<--format=..>.

=item B<-a адреса>

=item B<--add адреса>

Додати віддалений диск. Див. L<guestfish(1)/ДОДАВАННЯ ВІДДАЛЕНОГО СХОВИЩА>.

=item B<-c> адреса

=item B<--connect> адреса

Якщо використовується libvirt, встановити з’єднання з вказаним I<URI>. Якщо
пропущено, з’єднання буде встановлено з типовим гіпервізором libvirt.

Якщо вказати блокові пристрої гостьових систем безпосередньо (I<-a>),
libvirt не буде використовуватися взагалі.

=item B<-d> гість

=item B<--domain> гість

Додати всі диски з вказаної гостьової системи libvirt. UUID доменів можна
використовувати замість назв.

=item B<--echo-keys>

When prompting for keys and passphrases, virt-log normally turns echoing off
so you cannot see what you are typing.  If you are not worried about Tempest
attacks and there is no one else in the room you can specify this flag to
see what you are typing.

=item B<--format=raw|qcow2|..>

=item B<--format>

Типовим значенням для параметра I<-a> є автоматичне визначення формату
образу диска. Використання цього параметра примусово визначає значення
параметрів I<-a> формату диска у наступному рядку команди. Використання
параметра I<--format> без аргументу перемикає програму у режим автоматичного
визначення у наступних параметрах I<-a>.

Приклад:

 virt-log --format=raw -a диск.img

примусове встановлення формату без обробки (без автоматичного визначення)
для F<disk.img>.

 virt-log --format=raw -a диск.img --format -a інший.img

примусове встановлення формату без обробки (без автоматичного визначення)
для F<diskimg> і повернення до автоматичного визначення для F<another.img>.

Якщо ви користуєтеся ненадійними образами гостьових систем у необробленому
форматі, вам слід скористатися цим параметром для визначення формату
диска. Таким чином можна уникнути можливих проблем з захистом для
сформованих зловмисниками гостьових систем (CVE-2010-3851).

=item B<--keys-from-stdin>

Read key or passphrase parameters from stdin.  The default is to try to read
passphrases from the user by opening F</dev/tty>.

=item B<-v>

=item B<--verbose>

Увімкнути докладний показ повідомлень з метою діагностики.

=item B<-V>

=item B<--version>

Показати дані щодо версії і завершити роботу.

=item B<-x>

Увімкнути трасування викликів програмного інтерфейсу libguestfs.

=back

=head1 СТАН ВИХОДУ

Ця програма повертає значення 0 у разі успішного завершення і ненульове
значення, якщо сталася помилка.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfs(3)>, L<guestfish(1)>, L<virt-cat(1)>, L<virt-copy-out(1)>,
L<virt-tail(1)>, L<virt-tar-out(1)>, L<virt-win-reg(1)>,
L<http://libguestfs.org/>.

=head1 АВТОР

Richard W.M. Jones L<http://people.redhat.com/~rjones/>

=head1 АВТОРСЬКІ ПРАВА

Copyright (C) 2010-2017 Red Hat Inc.

