
=head1 НАЗВА

virt-tar-out — пакування каталогу на образі диска віртуальної машини до
архіву tar.

=head1 КОРОТКИЙ ОПИС

 virt-tar-out -a диск.img /каталог файли.tar

 virt-tar-out -d домен /каталог файли.tar

 virt-tar-out -d домен /каталог - | gzip --best > файли.tar.gz

=head1 ОПИС

C<virt-tar-out> пакує каталог на образі диска віртуальної машини до архіву
tar.

Першим параметром є абсолютний шлях до каталогу у віртуальній машині. Другим
параметром є файл архіву tar, до якого слід записати дані. Скорисайтеся
параметром C<->, щоб вивести дані до стандартного виведення.

=head1 ПРИКЛАДИ

Отримати домашні каталоги користувачів з гостьової операційної системи:

 virt-tar-out -d MyGuest /home - | gzip --best > homes.tar.gz

=head1 ПРОСТО СКРИПТ КОМАНДНОЇ ОБОЛОНКИ, ОБГОРТКА НАВКОЛО GUESTFISH

Ця програма є простим скриптом командної оболонки, обгорткою навколо команди
C<tar-out> L<guestfish(1)>. Якщо вам потрібно виконати якесь завдання,
складніше за звичайне копіювання, ймовірно, варто скористатися guestfish
безпосередньо.

=head1 ПАРАМЕТРИ

Оскільки скрипт командної оболонки лише передає параметри безпосередньо до
guestfish, ознайомтеся зі сторінкою підручника для L<guestfish(1)>, щоб
дізнатися більше про повний набір параметрів.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfish(1)>, L<virt-cat(1)>, L<virt-copy-in(1)>, L<virt-copy-out(1)>,
L<virt-edit(1)>, L<virt-tar-in(1)>, L<http://libguestfs.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2011–2012

