
=head1 НАЗВА

virt-list-filesystems — показ списку файлових систем у віртуальній машині
або на образі диска

=head1 КОРОТКИЙ ОПИС

 virt-list-filesystems [--параметри] -d назва_домену

 virt-list-filesystems [--параметри] образ.img [образ.img ...]

=head1 ЗАСТАРІЛЕ

Ця програма вважається застарілою. Замість неї слід використовувати програму
L<virt-filesystems(1)>, яке є гнучкішим замінником.

=head1 ОПИС

C<virt-list-filesystems> — інструмент командного рядка для показу списку
файлових систем, які містяться у віртуальній машині (або образі диска).

C<virt-list-filesystems> є простою обгорткою навколо L<libguestfs(3)>. Для
виконання складніших дій можна скористатися програмою L<guestfish(1)>.

=head1 ПАРАМЕТРИ

=over 4

=item B<--help>

Показати коротку довідку.

=item B<--version>

Показати дані щодо версії і завершити роботу.

=item B<-c адреса>

=item B<--connect адреса>

Якщо використовується libvirt, встановити з’єднання з вказаним I<URI>. Якщо
пропущено, з’єднання буде встановлено з типовим гіпервізором libvirt.

Якщо вказати блокові пристрої гостьових систем безпосередньо, libvirt не
буде використовуватися взагалі.

=item B<--format> raw

Визначає формат образу диска, назву якого вказано у рядку команди. Якщо
формат не вказано, його буде визначено автоматично на основі вмісту образу
диска.

Якщо вказаний диск походить з libvirt, ця програма надішле запит щодо даних
до libvirt. У цьому випадку вказане значення параметра формату буде
проігноровано.

Якщо ви працюєте із образами дисків гостьових систем у форматі raw із
ненадійних джерел, вам слід завжди вказувати назву формату.

=item B<-l>

=item B<--long>

Якщо вказано цей параметр, C<virt-list-filesystems> показує тип кожної
файлової системи (де під типом ми розуміємо C<ext3>, C<xfs> тощо)

=item B<-a>

=item B<--all>

Зазвичай, буде показано лише файлові системи, які придатні до
монтування. Якщо вказано цей параметр, програма показуватиме і пристрої
резервної пам'яті на диску.

=back

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfs(3)>, L<guestfish(1)>, L<virt-cat(1)>, L<virt-tar(1)>,
L<virt-filesystems(1)>, L<virt-list-partitions(1)>, L<Sys::Guestfs(3)>,
L<Sys::Virt(3)>, L<http://libguestfs.org/>.

=head1 АВТОР

Richard W.M. Jones L<http://people.redhat.com/~rjones/>

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2009

