
=head1 НАЗВА

virt-tar-in — розпаковування архіву tar до образу диска віртуальної машини.

=head1 КОРОТКИЙ ОПИС

 virt-tar-in -a диск.img дані.tar /призначення

 virt-tar-in -d домен дані.tar /призначення

 zcat дані.tar.gz | virt-tar-in -d домен - /призначення

=head1 ОПИС

C<virt-tar-in> unpacks an uncompressed tarball into a virtual machine disk
image or named libvirt domain.

The first parameter is the tar file.  Use C<-> to read the tar file from
standard input.  The second parameter is the absolute target directory to
unpack into.

=head1 ПРИКЛАДИ

Вивантаження домашнього каталогу до гостьової системи:

 virt-tar-in -d MyGuest homes.tar /home

=head1 ПРОСТО СКРИПТ КОМАНДНОЇ ОБОЛОНКИ, ОБГОРТКА НАВКОЛО GUESTFISH

Ця програма є простим скриптом командної оболонки, обгорткою навколо команди
C<tar-in> L<guestfish(1)>. Якщо вам потрібно виконати якесь завдання,
складніше за звичайне копіювання, ймовірно, варто скористатися guestfish
безпосередньо.

=head1 ПАРАМЕТРИ

Оскільки скрипт командної оболонки лише передає параметри безпосередньо до
guestfish, ознайомтеся зі сторінкою підручника для L<guestfish(1)>, щоб
дізнатися більше про повний набір параметрів.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfish(1)>, L<virt-cat(1)>, L<virt-copy-in(1)>, L<virt-copy-out(1)>,
L<virt-edit(1)>, L<virt-make-fs(1)>, L<virt-tar-out(1)>,
L<http://libguestfs.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2011–2012

