
=head1 НАЗВА

virt-copy-in — копіювання файлів та каталогів до образу диска віртуальної
машини.

=head1 КОРОТКИЙ ОПИС

 virt-copy-in -a диск.img файл|каталог [файл|каталог ...] /призначення

 virt-copy-in -d домен файл|каталог [файл|каталог ...] /призначення

=head1 ОПИС

C<virt-copy-in> копіює файли та каталоги з локального диска до образу диска
віртуальної машини або іменованого домену libvirt.

У рядку команди можна вказати одну або декілька назв файлів або
каталогів. Каталоги буде скопійовано рекурсивно. Останнім параметром має
бути каталог призначення на образі диску, який має бути вказано як
абсолютний шлях, що починається із символу F</>.

=head1 ПРИКЛАДИ

Оновлення F</etc/resolv.conf> у гостьовій системі:

 virt-copy-in -d MyGuest resolv.conf /etc

Вивантаження домашнього каталогу до гостьової системи:

 virt-copy-in -d MyGuest skel /home

=head1 ПРОСТО СКРИПТ КОМАНДНОЇ ОБОЛОНКИ, ОБГОРТКА НАВКОЛО GUESTFISH

Ця програма є простим скриптом командної оболонки, обгорткою навколо команди
C<copy-in> L<guestfish(1)>. Якщо вам потрібно виконати якесь завдання,
складніше за звичайне копіювання, ймовірно, варто скористатися guestfish
безпосередньо.

=head1 ПАРАМЕТРИ

Оскільки скрипт командної оболонки лише передає параметри безпосередньо до
guestfish, ознайомтеся зі сторінкою підручника для L<guestfish(1)>, щоб
дізнатися більше про повний набір параметрів.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfish(1)>, L<virt-cat(1)>, L<virt-copy-out(1)>, L<virt-edit(1)>,
L<virt-tar-in(1)>, L<virt-tar-out(1)>, L<http://libguestfs.org/>.

=head1 АВТОРИ

Richard W.M. Jones (C<rjones at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2011–2012

