
=head1 НАЗВА

virt-dib - виконати елементи diskimage-builder

=head1 КОРОТКИЙ ОПИС

 virt-dib -B DIB-LIB [параметри] елементи...

=head1 ОПИС

Virt-dib — інструмент для використання елементів C<diskimage-builder> з
метою побудови нового образу диска, створення нових дисків у пам'яті тощо.

Virt-dib призначено для безпечної заміни C<diskimage-builder> і її режиму
C<ramdisk-image-create>, див. L</ПОРІВНЯННЯ З DISKIMAGE-BUILDER>, щоб
ознайомитися із коротким порівнянням із використанням C<diskimage-builder>.

C<diskimage-builder> є частиною проекту TripleO OpenStack:
L<https://wiki.openstack.org/wiki/TripleO>.

=head1 ПРИКЛАДИ

=head2 Збирання простих образів дистрибутивів

 virt-dib \
   -B /шлях/до/diskimage-builder/lib \
   -p /шлях/до/diskimage-builder/elements \
   --envvar DIB_RELEASE=jessie \
   --name debian-jessie \
   debian vm

Ця команда збирає образ диска Debian Jessie (8.x), який є придатним для
запуску у форматі віртуальної машини, який буде збережено як
F<debian-jessie.qcow2>.

=head2 Збирання дисків у пам’яті

 virt-dib \
   -B /шлях/до/diskimage-builder/lib \
   -p /шлях/до/diskimage-builder/elements \
   --ramdisk \
   --name ramdisk \
   ubuntu deploy-ironic

Ця команда збирає диск у пам’яті для компонента Ironic OpenStack на основі
дистрибутива Ubuntu.

=head1 ПАРАМЕТРИ

=over 4

=item B<--help>

Показати довідкове повідомлення.

=item B<-B> ШЛЯХ

Встановити шлях до каталогу бібліотеки C<diskimage-builder>. Типово, це
підкаталог F<lib> у початкових кодах, а після встановлення до F</usr>
каталог F</usr/share/diskimage-builder/lib>.

Цей параметр є B<обов'язковим>, оскільки virt-dib має надати його елементам
(оскільки деякі з них можуть використовувати скрипти у каталозі). Сама ж
програма virt-dib не використовує цей каталог бібліотеки безпосередньо.

=item B<--arch> АРХІТЕКТУРА

Використовувати для образу-результату вказану архітектуру. Типовим є
значення, яке збігається зі значенням архітектури для основної системи, на
якій запущено virt-dib.

У поточній версії цей параметр виконує лише встановлення змінної середовища
C<ARCH> для елементів, а елементи вже створюють образ для потрібної
користувачу архітектури.

=item B<--checksum>

Створювати файли контрольних сум для образу. Підтримуваними є контрольні
суми MD5 та SHA256.

=item B<--colors>

=item B<--colours>

Використовувати послідовності символів ANSI для розфарбовування
повідомлень. Ці послідовності типово використовуються, якщо дані виводяться
на термінал tty.  Якщо дані, виведені програмою, спрямовуються до файла,
послідовності визначення кольорів ANSI буде вимкнено, якщо ви не додасте до
команди цей параметр.

=item B<--debug> РІВЕНЬ

Встановити значення рівня діагностики C<РІВЕНЬ>. Рівнем є невід'ємне ціле
число. Типовим є рівень C<0>.

Цей рівень діагностики відрізняється від рівня, який встановлюється I<-x> і
I<-v>, він збільшує обсяг діагностичної інформації, яка виводиться. Зокрема,
він встановлює C<DIB_DEBUG_TRACE>, усі значення рівня E<gt> C<0>
уможливлюють трасування у виконуваних скриптах.

=item B<--docker-target> ЦІЛЬ

Встановити сховище і мітку для docker.

Використовується лише тоді, коли серед форматів є C<docker>, і є
обов'язковим у цьому випадку.

=item B<--drive> ДИСК

Додати вказаний диск як допоміжний, такий, де зберігатимуться файли кешу
елементів, зокрема образи дисків, пакунки дистрибутива тощо.

Див. L</ДОПОМІЖНИЙ ДИСК>.

=item B<--drive-format> raw

=item B<--drive-format> qcow2

Вказати формат допоміжного диска. Якщо цей прапорець не вказано, його буде
автоматично визначено на основі даних самого диска.

Якщо ви працюєте із образами дисків гостьових систем у форматі raw із
ненадійних джерел, вам слід завжди вказувати назву формату.

Цей параметр використовується, лише якщо вказано I<--drive>.

Див. L</ДОПОМІЖНИЙ ДИСК>.

=item B<-p> ШЛЯХ

=item B<--element-path> ШЛЯХ

Додати новий шлях з елементами. Шляхи використовуватимуться у тому самому
порядку, у якому з’являються параметри I<-p>, отже, пошук за шляхом,
вказаним першим, відбуватиметься спочатку.

Очевидно, варто додати шлях до власних елементів C<diskimage-builder>,
оскільки більшість інших елементів покладатимуться на ці дані.

=item B<--extra-packages> ПАКУНОК,...

Встановити додаткові пакунки у образ, який збиратиметься.

Робота цього параметра залежить від виконуваного файла C<install-packages>,
який визначається елементами керування пакунками.

Цей параметр може бути використано декілька разів, декілька пакунків у
аргументах слід відокремлювати комами.

=item B<--envvar> ЗМІННА

=item B<--envvar> ЗМІННА=ЗНАЧЕННЯ

Передати або встановити змінну середовища для елементів.

Див. L</ЗМІННІ СЕРЕДОВИЩА> нижче, щоб дізнатися більше про взаємодію і
використання змінних середовища.

Цим параметром можна скористатися у декілька способів:

=over 4

=item B<--envvar> ЗМІННА

Передати змінну середовища C<ЗМІННА>. Якщо змінну не встановлено, до
елементів нічого не експортуватиметься.

=item B<--envvar> ЗМІННА=ЗНАЧЕННЯ

Встановити для змінної середовища C<ЗМІННА> значення C<ЗНАЧЕННЯ> для
елементів, незалежно від того, чи вже існує змінна середовища із тією самою
назвою.

Може бути корисним для передавання змінної середовища без експортування у
середовище, де запущено virt-dib.

=back

=item B<--exclude-element> ЕЛЕМЕНТ

Ігнорувати вказаний елемент.

=item B<--exclude-script> СКРИПТ

Ігнорувати будь-який скрипт елемента із назвою C<СКРИПТ>, байдуже, до якого
елемента він належатиме.

Це може бути корисним, якщо якийсь скрипт погано працює з virt-dib,
наприклад, якщо скриптові справді потрібне середовище C<diskimage-builder>.

=item B<--formats> ФОРМАТ,...

Встановити список форматів виведення даних, відокремлених комами.

Підтримувані формати:

=over 4

=item C<docker>

Імпортувати образ до docker за допомогою команди B<docker
import>. Призначення для образу B<має> бути вказано за допомогою
I<--docker-target>.

Будь ласка, зауважте, що виконання цієї дії зазвичай потребує вмикання
служби docker, інакше його не вдасться виконати. Крім того, B<docker> працює
з використанням L<sudo(8)>, отже, переконайтеся, що користувач має право
запускати принаймні B<docker>.

=item C<qcow2> (типово увімкнено)

qcow2 для QEMU. Для роботи з цим форматом потрібна програма C<qemu-img>.

=item C<raw>

Формат даних диска без обробки.

=item C<squashfs>

Файлова система squashfs, яку стиснуто за допомогою XZ. Для користування цим
форматом виведення даних потрібна можливість C<squashfs>; див. також
L<guestfs(3)/ДОСТУПНІСТЬ>.

=item C<tar>

Архів без стискання.

=item C<tgz>

Архів tar, стиснутий за допомогою gzip.

=item C<vhd>

Образ диска C<Virtual Hard Disk>. Виведення даних у цьому форматі вимагає
наявності C<vhd-util>.

Будь ласка, зверніть увагу на те, що версія C<vhd-util> повинна бути
зібраною із латкою, яка вмикає підтримку підкоманди C<convert>, і бути
придатною до завантаження. Латку можна знайти тут:
L<https://github.com/emonty/vhd-util/blob/master/debian/patches/citrix>.

=back

=item B<--fs-type> ФАЙЛОВА СИСТЕМА

Встановити файлову систему, яку буде використано для кореневої теки
системи. Типовою є C<ext4>.

Див. також L<guestfs(3)/guestfs_filesystem_available>

=item B<--image-cache> КАТАЛОГ

Встановити каталог у основній системі, до якого кешуватимуться ресурси, які
використовуються елементами фази C<extra-data.d>. Типовим є
F<~/.cache/image-create>.

Будь ласка, зауважте, що більшість ресурсів, які отримуватимуться на фазах,
відмінних від C<extra-data.d>, кешуватимуться на допоміжному диску,
вказаному за допомогою I<--drive>; див. також L</ДОПОМІЖНИЙ ДИСК>.

=item B<--install-type> ТИП

Вказати типовий тип встановлення. Стандартним є C<source>.

Встановіть значення C<package>, щоб типово використовувати засноване на
пакунках встановлення.

=item B<--machine-readable>

=item B<--machine-readable>=format

За допомогою цього параметра можна зробити виведені дані придатнішими для
обробки комп'ютером, якщо для цієї обробки використовуються інші
програми. Див. L</ПРИДАТНЕ ДО ЧИТАННЯ КОМП'ЮТЕРОМ ВИВЕДЕННЯ> нижче.

=item B<-m> МБ

=item B<--memsize> МБ

Змінити обсяг пам'яті, який надаватиметься для базової системи. Збільште це
значення, якщо для виконання virt-dib не вистачає пам'яті.

Типові значення можна визначити за допомогою такої команди:

 guestfish get-memsize

=item B<--mkfs-options> C<РЯДОК ПАРАМЕТРІВ>

Додати вказані параметри до L<mkfs(1)>, щоб мати змогу скоригувати параметри
створення кореневої файлової системи; параметри передаються драйверу
L<mfks(1)>, а не самій L<mfks(1)>. Зауважте, що для зміни типу файлової
системи використовується I<--fs-type>.

Вам слід скористатися I<--mkfs-options> не більше одного разу. Щоб передати
декілька параметрів, відокремте їх пробілами. Приклад:

 virt-dib ... --mkfs-options '-O якийсь_параметр -I щось_ще'

=item B<--network>

=item B<--no-network>

Увімкнути чи вимкнути доступ до мережі для гостьової системи під час
встановлення.

Типово увімкнено. Скористайтеся параметром I<--no-network>, щоб вимкнути
доступ.

У мережі працюватимуть лише вихідні з'єднання, а також буде декілька інших
незначних обмежень. Див. L<virt-rescue(1)/МЕРЕЖА>.

Це не вплине на доступність мережі для гостьової системи після її
завантаження, оскільки така доступність керується вашим гіпервізором або
хмарним середовищем і не має нічого спільного з virt-dib.

Якщо ви використаєте параметр I<--no-network>, змінній середовища
C<DIB_OFFLINE> буде надано значення C<1>, що сигналізуватиме елементам про
те, що їм слід використовувати лише кешовані ресурси, якщо вони
доступні. Також слід зауважити, що, на відміну від C<diskimage-builder>, де
елементи все ще можуть отримувати доступ до мережі навіть із
C<DIB_OFFLINE=>, у virt-dib мережа буде зовсім недоступною.

=item B<--name> НАЗВА

Встановити назву для файла із виведеним образом. Типовою є C<image>.

Відповідно до вибраної назви, у поточному каталозі буде таке:

=over 4

=item F<$NAME.ext>

Для кожного з форматів виведення назву файла буде взято з назви
образу-результату, а суфікс назви залежатиме від формату. Приклад:
F<$NAME.qcow2>, F<$NAME.raw> тощо.

Не можна застосовувати у режимі диска у пам'яті (ramdisk), див. L</ЗБИРАННЯ
ДИСКА У ПАМ'ЯТІ>.

=item F<$NAME.d>

Каталог, що містить будь-які файли, створені елементами, наприклад каталог
F<dib-manifests> (створено елементом C<manifests>), диски у пам'яті та ядра
у режимі диску у пам'яті тощо.

=item F<$NAME.ext.checksum>

Якщо вказано I<--checksum>, буде створено файли для усіх підтримуваних типів
контрольних сум; приклади: F<$NAME.ext.md5>, F<$NAME.ext.sha256> тощо.

Не можна застосовувати у режимі диска у пам'яті (ramdisk), див. L</ЗБИРАННЯ
ДИСКА У ПАМ'ЯТІ>.

=back

=item B<--no-delete-on-failure>

Не вилучати файли з виведеними даними, якщо під час збирання станеться
помилка. Цими файлами можна скористатися для діагностики помилок у запущених
скриптах.

Типовою є поведінка, коли файли результатів буде вилучено, якщо станеться
помилка у virt-dib (або, наприклад, помилка у одному зі скриптів, які
запускає ця програма).

=item B<--python> PYTHON

Вказати для використання інший інтерпретатор Python. Частину
C<diskimage-builder> реалізовано мовою Python, тому інтерпретатор є
обов'язковим.

Значенням C<PYTHON> може бути або повна назва виконуваного файла (наприклад
F<python2>, пошук якого буде виконано у каталогах змінної C<$PATH>), або
шлях повністю (наприклад  F</usr/bin/python2>). Якщо не вказано, типовим
значенням буде F<python>.

=item B<-q>

=item B<--quiet>

Не виводити звичайних повідомлень щодо поступу.

=item B<--qemu-img-options> параметр[,параметр,...]

Передати параметри I<--qemu-img-options> до програми L<qemu-img(1)> для
коригування формату виведення даних.  Перелік доступних параметрів залежить
від формату виведення (див. I<--formats>) і встановленої версії програми
qemu-img.

Вам слід скористатися I<--qemu-img-options> не більше одного разу. Щоб
передати декілька параметрів, відокремте їх комами. Приклад:

 virt-dib ... --qemu-img-options cluster_size=512,preallocation=metadata ...

=item B<--ramdisk>

Встановити режим збирання диска у пам’яті.

Див. L</ЗБИРАННЯ ДИСКА У ПАМ'ЯТІ>.

=item B<--ramdisk-element> НАЗВА

Встановити назву для додаткового елемента, який буде додано у режимі
збирання диска у пам'яті. Типовою є назва C<ramdisk>.

Див. L</ЗБИРАННЯ ДИСКА У ПАМ'ЯТІ>.

=item B<--root-label> МІТКА

Встановити мітку для кореневої файлової системи у створеному образі.

Будь ласка, зауважте, що у деяких файлових системах обмеження на мітки може
бути іншим. Наприклад, у файлових системах C<ext2/3/4> мітки не можуть бути
довшими за 16 символів, а у C<xfs> найбільшою довжиною мітки є 12 символів.

Типове значення залежить від типу файлової системи для кореневого розділу
(див. I<--fs-type>): на C<xfs> — це C<img-rootfs>, а на будь-якій іншій
файловій системі — C<cloudimg-rootfs>.

=item B<--size> РОЗМІР

Вибір розміру диска-результату, де розмір можна вказати за допомогою типових
записів, зокрема C<32G> (32 гігабайти) тощо. Типовим є розмір C<5G>.

Щоб вказати розмір у байтах, додайте до числа малу літеру I<b>, наприклад
S<C<--size 10737418240b>>.

Див. також L<virt-resize(1)> щодо зміни розмірів розділів на наявному образі
диска.

=item B<--skip-base>

Пропустити включення елемента C<base>.

=item B<--smp> N

Увімкнути використання скриптами N E<ge> 2 віртуальних процесорів.

=item B<-u>

Не стискати отримані образи qcow2. Типово, програма стискає такі образи.

=item B<-v>

=item B<--verbose>

Увімкнути показ діагностичних повідомлень.

=item B<-V>

=item B<--version>

Показати дані щодо версії і завершити роботу.

=item B<-x>

Увімкнути трасування викликів програмного інтерфейсу libguestfs.

=back

=head1 ЗМІННІ СЕРЕДОВИЩА

На відміну від C<diskimage-builder>, середовище основної системи B<не>
успадковується у базовій системі під час запуску більшості елементів (тобто
усіх, окрім елементів у фазі C<extra-data.d>).

Щоб встановити змінні середовища для виконання елементів, слід повідомити
virt-dib, що слід використовувати ці змінні, за допомогою параметра
I<--envvar>.  Такий параметр надасть змогу вибірково експортувати змінні
середовища під час виконання елементі. Це також пріоритетний шлях
передавання змінних середовища елементам.

І ще раз: якщо вам потрібно, щоб змінна середовища C<MYVAR> (і її вміст)
були доступні елементам, вам слід або віддати команду

 export MYVAR   # яким би не було її значення
 virt-dib ... --envvar MYVAR ...

або

 virt-dib ... --envvar MYVAR=її_значення ...

=head1 ДОПОМІЖНИЙ ДИСК

Virt-dib виконує більшість елементів у власній базовій системі, отже, не на
основній системі. Через це, елементи не можуть кешувати ресурси
безпосередньо на основній системі.

Щоб усунути цю незручність, у virt-dib передбачено можливість використання
допоміжного диска, на якому можна зберігати кешовані ресурси, зокрема образи
дисків, пакунки дистрибутивів тощо. Хоча це означає, що для кешування буде
доступним менше місця, принаймні, це надає змогу обмежити простір у основній
системі для кешів без потреби у виконанні цього завдання засобами самих
елементів.

У поточній версії або цей диск має містити лише один розділ, або має
використовуватися лише перший розділ з диска. Диск із другим варіантом
конфігурації доволі просто створити за допомогою L<guestfish(1)> ось так:

 guestfish -N filename.img=fs:ext4:10G exit

У результаті виконання наведеної вище команди буде створено образ диска із
назвою F<filename.img> об'ємом у 10 ГБ з одним розділом типу ext4;
див. L<guestfish(1)/ОБРАЗИ ПРИГОТОВАНИХ ДИСКІВ>.

Рекомендованим розміром диска є E<ge> 10 ГБ, оскільки елементи кешуватимуть
образи дисків, пакунки дистрибутивів тощо. Як і розмір будь-якого образу
диска, розмір допоміжного диска можна змінити за допомогою
L<virt-resize(1)>, якщо раптом він стане замалим.

Доступ до диска може здійснюватися у спосіб, який є подібним до способу
доступу до будь-яких інших образів дисків, наприклад, за допомогою інших
інструментів libguestfs, зокрема L<guestfish(1)>:

 guestfish -a filename.img -m /dev/sda1

Якщо за допомогою I<--drive> не вказано жодного допоміжного диска, усі
ресурси, кешовані під час запуску virt-dib, буде відкинуто.

=head2 РЕСУРСИ НА ДИСКУ

У допоміжному диску можна шукати такі ресурси:

=over 4

=item F</home>

Цей каталог задається за допомогою змінної середовища C<HOME> під час
збирання. У ньому, здебільшого, міститься кеш образів (збережений до
F</home/.cache/image-create>) та усі інші ресурси у домашньому каталозі
користувача, який запускає різні інструменти.

=item F</virt-dib-*.log>

Це журнали елементів, які виконуються у базовій системі libguestfs, тобто
усі фази, окрім C<extra-data.d>.

=back

=head1 ЗБИРАННЯ ДИСКА У ПАМ'ЯТІ

Virt-dib може також емулювати C<ramdisk-image-create>, вторинний режим
роботи C<diskimage-builder>. Замість використання якогось інструмента із
іншою назвою, virt-dib надає простий доступ до режиму за допомогою параметра
I<--ramdisk>.

У цьому режимі:

=over 4

=item 

додається елемент ramdisk (див. I<--ramdisk-element>)

=item 

образу не створюється (отже, I<--formats> буде проігноровано)

=item 

F<$NAME.d> (див. I<--name>) міститиме initrd, kernel, тощо.

=back

=head1 ТИМЧАСОВИЙ КАТАЛОГ

Virt-dib використовує стандартний каталог для тимчасових файлів, який
використовується libguestfs, див. L<guestfs(3)/ЗМІННІ СЕРЕДОВИЩА>.

Типово, цим каталогом є F</tmp> (типове значення для C<TMPDIR>). У деяких
системах для цього каталогу може використовуватися файлова система
tmpfs. Таким чином, типовим максимальним розміром для нього є I<половина>
фізичного розміру оперативної пам'яті. Якщо під час роботи virt-dib
перевищить це обмеження, програма може повиснути або завершити роботу
передчасно із повідомленням про помилку. Усунути цю проблему можна, вказавши
для C<TMPDIR> тимчасовий каталог. Приклад:

 mkdir local-tmp
 env TMPDIR=$PWD/local-tmp virt-dib ...
 rm -rf local-tmp

=head1 ДОДАТКОВІ ЗАЛЕЖНОСТІ

Оскільки virt-dib запускає більшість елементів у власній базовій системі,
усі інструменти та бібліотеки, які використовуються елементами, що
запускаються поза межами гостьової системи (типово C<root.d>,
C<block-device.d> та C<cleanup.d>) мають бути і у базовій системі. Якщо їх
не буде, скрипти не зможуть працювати і типово повідомлять про помилку
C<команду не знайдено>.

Для інструментів і бібліотек, які містяться у пакунках дистрибутивів,
простим рішенням цієї проблеми буде віддання наказу libguestfs включити
додаткові пакунки до базової системи. Зробити це можна, наприклад, створення
файла із додатковими пакунками:

 # echo wget > /usr/lib64/guestfs/supermin.d/dib-my-extra

Шлях до каталогу F<supermin.d>, звичайно ж, залежить від дистрибутива. У
додаткових файлах може бути список із багатьма пакунками, кожен з яких слід
вказувати окремому рядку. Докладніший опис можна знайти у підручнику з
L<supermin(1)>.

=head1 ПОРІВНЯННЯ ІЗ DISKIMAGE-BUILDER

Призначенням virt-dib є бути безпечним замінником програми
C<diskimage-builder> і її режиму C<ramdisk-image-create>. Помітні для
користувача відмінності полягають ось у чому:

=over 4

=item 

аргументи командного рядка; деякі з аргументів збігаються із аргументами
C<diskimage-builder>, але деякі є іншими:

 disk-image-create             virt-dib
 -----------------             --------
 -a ARCH                       --arch АРХІТЕКТУРА
 --image-size РОЗМІР           --size РОЗМІР
 --max-online-resize РОЗМІР    doable using --mkfs-options
 -n                            --skip-base
 -o НАЗВА ОБРАЗУ               --name НАЗВА ОБРАЗУ
 -p ПАКУНКИ                    --extra-packages ПАКУНКИ
 -t ФОРМАТИ                    --formats ФОРМАТИ
 -x                            --debug 1
 -x -x                         --debug 2
 -x -x [-x ...]                --debug 3/4/etc

=item 

розташування файлів-результатів, які не є образами (зокрема дисків у пам'яті
і ядер)

=item 

спосіб зберігання деяких кешованих ресурсів: використання допоміжного диска,
а не диска, на якому запущено virt-dib

=item 

потреба у визначення розміру диска-результату, тоді як програма
C<diskimage-builder> автоматично обчислює оптимальний розмір

=item 

обробка змінних середовища, див. L</ЗМІННІ СЕРЕДОВИЩА>.

До того ж, окрім власних змінних середовища libguestfs
(див. L<guestfs(3)/ЗМІННІ СЕРЕДОВИЩА>), virt-dib не виконує читання жодних
інших змінних середовища. Це означає, що зміни у параметрах і поведінці
програми визначаються лише переданими їй аргументами рядка команди.

=item 

потрібно, щоб додаткові інструменти на деяких фазах поза chroot були
доступні у базовій системі, див. L</ДОДАТКОВІ ЗАЛЕЖНОСТІ>.

=back

Робота самих елементів не повинна зазнати змін; причиною відмінностей у
поведінці можуть бути помилкові припущення у коді самих елементів або
некоректна емуляція virt-dib.

Відомі вади:

=over 4

=item 

(нічого)

=back

=head1 ПРИДАТНЕ ДО ЧИТАННЯ КОМП'ЮТЕРОМ ВИВЕДЕННЯ

Для виведення даних у зручному для машинної обробки форматі можна
скористатися параметром I<--machine-readable>. Додавання цього параметра
робить зручним використання virt-dib з інших програм, графічних інтерфейсів
тощо.

Скористайтеся цим параметром окремо, щоб опитати систему щодо можливостей
виконуваного файла virt-dib.  Типово виведені дані виглядатимуть якось так:

 $ virt-dib --machine-readable
 virt-dib
 output:qcow2
 output:tar
 output:raw
 output:vhd

Виводиться список можливостей, по одній на рядок, і програма завершує роботу
зі станом 0.

C<output:> є вказівкою на формати виведення (параметр рядка команди
I<--formats>), підтримку яких передбачено у цьому виконуваному файлі.

It is possible to specify a format string for controlling the output; see
L<guestfs(3)/ADVANCED MACHINE READABLE OUTPUT>.

=head1 ТЕСТУВАННЯ

Перевірку працездатності virt-dib було виконано для C<diskimage-builder> (та
його елементів)  E<ge> 0.1.43. Час від часу виконується також перевірка для
C<tripleo-image-elements> та C<sahara-image-elements>.

Попередні версії також можуть працювати, але цього не можна гарантувати.

=head1 СТАН ВИХОДУ

Ця програма повертає значення 0 у разі успішного завершення і ненульове
значення, якщо сталася помилка.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfs(3)>, L<guestfish(1)>, L<virt-resize(1)>,
L<http://libguestfs.org/>.

=head1 АВТОР

Pino Toscano (C<ptoscano at redhat dot com>)

=head1 АВТОРСЬКІ ПРАВА

© Red Hat Inc., 2015

