
=head1 НАЗВА

virt-customize - Customize a virtual machine

=head1 КОРОТКИЙ ОПИС

 virt-customize [--options] -d domname
__CUSTOMIZE_SYNOPSIS__

 virt-customize [--options] -a disk.img [-a disk.img ...]
__CUSTOMIZE_SYNOPSIS__

=head1 ОПИС

Virt-customize can customize a virtual machine (disk image) by installing
packages, editing configuration files, and so on.

Virt-customize modifies the guest or disk image I<in place>.  The guest must
be shut down.  If you want to preserve the existing contents of the guest,
I<you must snapshot, copy or clone the disk first>.

You do I<not> need to run virt-customize as root.  In fact we'd generally
recommend that you don't.

Related tools include: L<virt-sysprep(1)> and L<virt-builder(1)>.

=head1 ПАРАМЕТРИ

=over 4

=item B<--help>

Показати коротку довідку.

=item B<-a> файл

=item B<--add> файл

Додати I<файл>, який має бути образом диска з віртуальної машини.

Формат образу диска визначається автоматично. Щоб перевизначити його і
примусово використати певний формат, скористайтеся параметром I<--format>.

=item B<-a> адреса

=item B<--add> адреса

Add a remote disk.  The URI format is compatible with guestfish.  See
L<guestfish(1)/ADDING REMOTE STORAGE>.

=item B<--attach> ФАЙЛ_ISO

The given disk is attached to the libguestfs appliance.  This is used to
provide extra software repositories or other data for customization.

You probably want to ensure the volume(s) or filesystems in the attached
disks are labelled (or use an ISO volume name) so that you can mount them by
label in your run-scripts:

 mkdir /tmp/mount
 mount LABEL=EXTRA /tmp/mount

You can have multiple I<--attach> options, and the format can be any disk
format (not just an ISO).

=item B<--attach-format> ФОРМАТ

Specify the disk format for the next I<--attach> option.  The C<FORMAT> is
usually C<raw> or C<qcow2>.  Use C<raw> for ISOs.

=item B<-c> адреса

=item B<--connect> адреса

Якщо використовується libvirt, встановити з’єднання з вказаним I<URI>. Якщо
пропущено, з’єднання буде встановлено з типовим гіпервізором libvirt.

Якщо вказати блокові пристрої гостьових систем безпосередньо (I<-a>),
libvirt не буде використовуватися взагалі.

=item B<-d> гість

=item B<--domain> гість

Додати всі диски з вказаної гостьової системи libvirt. UUID доменів можна
використовувати замість назв.

=item B<-n>

=item B<--dry-run>

Perform a read-only "dry run" on the guest.  This runs the sysprep
operation, but throws away any changes to the disk at the end.

=item B<--format> raw|qcow2|..

=item B<--format> auto

Типовим значенням для параметра I<-a> є автоматичне визначення формату
образу диска. Використання цього параметра примусово визначає значення
параметрів I<-a> формату диска у наступному рядку команди. Використання
параметра I<--format auto> перемикає програму у режим автоматичного
визначення у наступних параметрах I<-a>.

Приклад:

 virt-customize --format raw -a disk.img

примусове встановлення формату без обробки (без автоматичного визначення)
для C<disk.img>.

 virt-customize --format raw -a disk.img --format auto -a another.img

примусове встановлення формату без обробки (без автоматичного визначення)
для C<disk.img> і повернення до автоматичного визначення для C<another.img>.

Якщо ви користуєтеся ненадійними образами гостьових систем у необробленому
форматі, вам слід скористатися цим параметром для визначення формату
диска. Таким чином можна уникнути можливих проблем з захистом для
сформованих зловмисниками гостьових систем (CVE-2010-3851).

=item B<-m> MB

=item B<--memsize> MB

Change the amount of memory allocated to I<--run> scripts.  Increase this if
you find that I<--run> scripts or the I<--install> option are running out of
memory.

The default can be found with this command:

 guestfish get-memsize

=item B<--network>

=item B<--no-network>

Enable or disable network access from the guest during the installation.

Enabled is the default.  Use I<--no-network> to disable access.

The network only allows outgoing connections and has other minor
limitations.  See L<virt-rescue(1)/NETWORK>.

If you use I<--no-network> then certain other options such as I<--install>
will not work.

This does not affect whether the guest can access the network once it has
been booted, because that is controlled by your hypervisor or cloud
environment and has nothing to do with virt-customize.

Generally speaking you should I<not> use I<--no-network>.  But here are some
reasons why you might want to:

=over 4

=item 1.

Because the libguestfs backend that you are using doesn't support the
network.  (See: L<guestfs(3)/BACKEND>).

=item 2.

Any software you need to install comes from an attached ISO, so you don't
need the network.

=item 3.

You don't want untrusted guest code trying to access your host network when
running virt-customize.  This is particularly an issue when you don't trust
the source of the operating system templates.  (See L</SECURITY> below).

=item 4.

You don't have a host network (eg. in secure/restricted environments).

=back

=item B<-q>

=item B<--quiet>

Не виводити повідомлень до журналу.

To enable detailed logging of individual file operations, use I<-x>.

=item B<--smp> N

Enable N E<ge> 2 virtual CPUs for I<--run> scripts to use.

=item B<-v>

=item B<--verbose>

Увімкнути докладний показ повідомлень з метою діагностики.

=item B<-V>

=item B<--version>

Показати дані щодо версії і завершити роботу.

=item B<-x>

Увімкнути трасування викликів програмного інтерфейсу libguestfs.

=back

=head2 Customization options

__CUSTOMIZE_OPTIONS__

=head1 SELINUX

For guests which make use of SELinux, special handling for them might be
needed when using operations which create new files or alter existing ones.

For further details, see L<virt-builder(1)/SELINUX>.

=head1 СТАН ВИХОДУ

This program returns 0 on success, or 1 if there was an error.

=head1 ЗМІННІ СЕРЕДОВИЩА

=over 4

=item C<VIRT_TOOLS_DATA_DIR>

This can point to the directory containing data files used for Windows
firstboot installation.

Normally you do not need to set this.  If not set, a compiled-in default
will be used (something like C</usr/share/virt-tools>).

Цей каталог може містити такі файли:

=over 4

=item C<rhsrvany.exe>

This is the RHSrvAny Windows binary, used to install a "firstboot" script in
Windows guests.  It is required if you intend to use the I<--firstboot> or
I<--firstboot-command> options with Windows guests.

Див. також C<https://github.com/rwmjones/rhsrvany>

=back

=back

Опис інших змінних середовища наведено у розділі L<guestfs(3)/ENVIRONMENT
VARIABLES>.

=head1 ТАКОЖ ПЕРЕГЛЯНЬТЕ

L<guestfs(3)>, L<guestfish(1)>, L<virt-builder(1)>, L<virt-clone(1)>,
L<virt-rescue(1)>, L<virt-resize(1)>, L<virt-sparsify(1)>,
L<virt-sysprep(1)>, L<virsh(1)>, L<lvcreate(8)>, L<qemu-img(1)>,
L<scrub(1)>, L<http://libguestfs.org/>, L<http://libvirt.org/>.

=head1 АВТОРИ

Richard W.M. Jones L<http://people.redhat.com/~rjones/>

=head1 АВТОРСЬКІ ПРАВА

Copyright (C) 2011-2015 Red Hat Inc.

