/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rc_protocol.h"

bool_t
xdr_guestfish_str (XDR *xdrs, guestfish_str *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_guestfish_hello (XDR *xdrs, guestfish_hello *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->vers, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_guestfish_call (XDR *xdrs, guestfish_call *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->cmd, ~0))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->args.args_val, (u_int *) &objp->args.args_len, ~0,
		sizeof (guestfish_str), (xdrproc_t) xdr_guestfish_str))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->exit_on_error))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_guestfish_reply (XDR *xdrs, guestfish_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->r))
		 return FALSE;
	return TRUE;
}
